image:
  name: ghcr.io/getzola/zola:v0.20.0
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - zola build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
