image:
  name: ghcr.io/getzola/zola:v0.20.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - build
  artifacts:
    paths:
      - public
    expire_in: never
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
